front/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from front.views import CoverageView, HomeView, QuotationView, PurchaseView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^sucesso', TemplateView.as_view(template_name='front/sucess.html'), name='success'),
    url(r'^pesquisa/(?P<slug>[\w-]+)/(?P<begin_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        QuotationView.as_view(), name='quotation'),
    url(r'^cobertura/(?P<product_id>\d+)/(?P<slug>[\w-]+)/(?P<begin_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        CoverageView.as_view(), name='coverage'),
    url(r'^pedido/(?P<product_id>\d+)/(?P<slug>[\w-]+)/(?P<begin_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        PurchaseView.as_view(), name='order'),
]

purchase/urls.py
from django.conf.urls import url
from purchase.views import DetailPurchase, ListPurchase

urlpatterns = [
    url(r'^$', ListPurchase.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', DetailPurchase.as_view(), name='detail'),
]

segurospromo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
     url(r'^', include('front.urls', namespace='front')),
     url(r'^compras/', include('purchase.urls', namespace='purchase')),
     url(r'^admin/', admin.site.urls),
]

purchase/models.py
from django.db import models


class Purchase(models.Model):
    """ Model by save data from a purchase """

    class Meta:
        app_label = 'purchase'
        ordering = ('pk', )

    begin_date = models.DateField()
    end_date = models.DateField()
    destination = models.CharField(max_length=50)
    product_id = models.PositiveIntegerField()
    insured_cpf = models.CharField(max_length=14)
    insured_name = models.CharField(max_length=100)
    insured_birth = models.DateField()
    card_name = models.CharField(max_length=100)
    card_cpf = models.CharField(max_length=14)
    card_number = models.CharField(max_length=16)
    card_mouth = models.CharField(max_length=2)
    card_year = models.CharField(max_length=4)
    card_cvv = models.CharField(max_length=4)
    buy_name = models.CharField(max_length=100)
    buy_email = models.CharField(max_length=100)
    buy_phone = models.CharField(max_length=20)
    product_name = models.CharField(max_length=250)
    provider_name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return "{} - {}".format(self.insured_name, self.product_name)

purchase/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from purchase.models import Purchase


class ListPurchase(ListView):
    model = Purchase


class DetailPurchase(DetailView):
    model = Purchase

purchase/templates/purchase/purchase_detail.html
{% extends 'front/base.html' %}
{% block title %}Seguros Promo - Detalhe da Compra{% endblock %}
{% block content %}
<h1>Detalhe da Compra {{ object.pk }}</h1>
<div>
  <p>Nome: {{ object.insured_name }}</p>
  <p>CPF: {{ object.insured_cpf }}</p>
  <p>Seguradora: {{ object.provider_name }} </p>
  <p>Destino: {{ object.destination }}</p>
  <p>Início: {{ object.begin_date }}</p>
  <p>Término: {{ object.end_date }}</p>
  <p>Valor: R$ {{ object.price|floatformat:2 }} </p>
  <p>Cartão: {{ object.card_number }}</p>
  <p>Cartão - CVV: {{ object.card_cvv }}</p>
</div>
{% endblock %}

purchase/templates/purchase/purchase_list.html
{% extends 'front/base.html' %}
{% block title %}Seguros Promo - Compras{% endblock %}
{% block content %}
<h1>Compras realizadas</h1>
<table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Início</th>
        <th>Fim</th>
        <th></th>
      </tr>
    </thead>
    {% for purchase in object_list %}
      <tbody>
        <tr>
            <td>{{ purchase.insured_name }}</td>
            <td>{{ purchase.insured_cpf }}</td>
            <td>{{ purchase.begin_date }}</td>
            <td>{{ purchase.end_date }}</td>
            <td><a href="{% url 'purchase:detail' purchase.pk %}" class="btn btn-success">Detalhe</a></td>
        </tr>
      </tbody>
    {% endfor %}
</table>
{% endblock %}