front/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from front.views import CoverageView, HomeView, QuotationView, PurchaseView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^sucesso', TemplateView.as_view(template_name='front/sucess.html'), name='success'),
    url(r'^pesquisa/(?P<slug>[\w-]+)/(?P<begin_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        QuotationView.as_view(), name='quotation'),
    url(r'^cobertura/(?P<product_id>\d+)/(?P<slug>[\w-]+)/(?P<begin_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        CoverageView.as_view(), name='coverage'),
    url(r'^pedido/(?P<product_id>\d+)/(?P<slug>[\w-]+)/(?P<begin_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$',
        PurchaseView.as_view(), name='order'),
]

purchase/urls.py
from django.conf.urls import url
from purchase.views import DetailPurchase, ListPurchase

urlpatterns = [
    url(r'^$', ListPurchase.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', DetailPurchase.as_view(), name='detail'),
]

segurospromo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
     url(r'^', include('front.urls', namespace='front')),
     url(r'^compras/', include('purchase.urls', namespace='purchase')),
     url(r'^admin/', admin.site.urls),
]

front/models.py
from django.db import models

purchase/models.py
from django.db import models


class Purchase(models.Model):
    """ Model by save data from a purchase """

    class Meta:
        app_label = 'purchase'
        ordering = ('pk', )

    begin_date = models.DateField()
    end_date = models.DateField()
    destination = models.CharField(max_length=50)
    product_id = models.PositiveIntegerField()
    insured_cpf = models.CharField(max_length=14)
    insured_name = models.CharField(max_length=100)
    insured_birth = models.DateField()
    card_name = models.CharField(max_length=100)
    card_cpf = models.CharField(max_length=14)
    card_number = models.CharField(max_length=16)
    card_mouth = models.CharField(max_length=2)
    card_year = models.CharField(max_length=4)
    card_cvv = models.CharField(max_length=4)
    buy_name = models.CharField(max_length=100)
    buy_email = models.CharField(max_length=100)
    buy_phone = models.CharField(max_length=20)
    product_name = models.CharField(max_length=250)
    provider_name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return "{} - {}".format(self.insured_name, self.product_name)

front/forms.py
from django import forms
from api.models import Destinations
from localflavor.br.forms import BRCPFField, BRPhoneNumberField


class CommonForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(CommonForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.attrs.get('class'):
                field.widget.attrs['class'] = 'form-control ' + \
                    field.widget.attrs['class']
            else:
                field.widget.attrs['class'] = 'form-control'


class FormQuotation(CommonForm):
    def __init__(self, *args, **kwargs):
        super(FormQuotation, self).__init__(*args, **kwargs)
        destinations = Destinations()
        self.fields['destiny'].choices = (
            (d.get('slug'), d.get('name')) for d in destinations.list())

    destiny = forms.ChoiceField(label="Destino")
    begin_date = forms.DateField(
        label="Partida", widget=forms.widgets.DateInput(
            attrs={'class': 'date'}))
    end_date = forms.DateField(
        label="Retorno", widget=forms.widgets.DateInput(
            attrs={'class': 'date'}))


class FormPurchase(CommonForm):
    insured_cpf = BRCPFField(label="CPF")
    insured_name = forms.CharField(max_length=100, label="Nome")
    birth_date = forms.DateField(
        label="Data de Nascimento", widget=forms.widgets.DateInput(
            attrs={'class': 'date'}))
    card_name = forms.CharField(max_length=100, label="Nome no cartão")
    card_cpf = BRCPFField(label="CPF")
    card_number = forms.CharField(max_length=16, label="Número do cartão")
    card_mouth = forms.ChoiceField(choices=(
        ('', '--'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
    ), label="Validade mês")
    card_year = forms.ChoiceField(choices=(
        ('', '----'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020'),
        ('2021', '2021'),
        ('2022', '2022'),
        ('2023', '2023'),
        ('2024', '2024'),
        ('2025', '2025'),
        ('2026', '2026'),
        ('2027', '2027'),
        ('2028', '2028'),
        ('2029', '2029'),
        ('2030', '2030'),
        ('2031', '2031'),

    ), label="Validade ano")
    card_cvv = forms.CharField(max_length=4, label="CVV")
    buy_name = forms.CharField(max_length=100, label="Nome para contato")
    buy_email = forms.EmailField(label="Email para contato")
    buy_phone = BRPhoneNumberField(label="Telefone para contato")

front/views.py
import json
from datetime import datetime

from django.core.urlresolvers import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

from api.models import Destinations, Products, Quotation
from purchase.models import Purchase
from front.forms import FormQuotation, FormPurchase
from front.utils import json2obj


class HomeView(View):
    form_class = FormQuotation
    template_name = 'front/home.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse(
                'front:quotation',
                kwargs={
                    'slug': form.cleaned_data.get('destiny'),
                    'begin_date': "{:%Y-%m-%d}".format(
                        form.cleaned_data.get('begin_date')),
                    'end_date': "{:%Y-%m-%d}".format(
                        form.cleaned_data.get('end_date')),
                }
            ))

        return render(request, self.template_name, {'form': form})


class QuotationView(View):
    form_class = FormQuotation
    template_name = 'front/quotation.html'

    def get(self, request, *args, **kwargs):
        begin_date = datetime.strptime(
            kwargs.get('begin_date'), '%Y-%m-%d')
        end_date = datetime.strptime(
            kwargs.get('end_date'), '%Y-%m-%d')
        form = self.form_class(initial={
            'destiny': kwargs.get('slug'),
            'begin_date': begin_date,
            'end_date': end_date,
        })
        quotations = Quotation()
        products = Products()
        quotations = quotations.calculate(
            destination=kwargs.get('slug'),
            begin_date=begin_date,
            end_date=end_date
        )
        for quotation in quotations:
            product = products.list(quotation.get('code'))
            hospital_care = [e for e in product.get(
                'benefits') if e['code'] == '50'][0].get('coverage')
            luggage_insurance = [e for e in product.get(
                'benefits') if e['code'] == '42'][0].get('coverage')
            quotation['hospital_care'] = hospital_care
            quotation['luggage_insurance'] = luggage_insurance

        quotations = json.dumps(quotations)
        quotations = json2obj(quotations)
        return render(
            request, self.template_name,
            {'form': form, 'quotations': quotations})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(reverse(
                'front:quotation',
                kwargs={
                    'slug': form.cleaned_data.get('destiny'),
                    'begin_date': "{:%Y-%m-%d}".format(
                        form.cleaned_data.get('begin_date')),
                    'end_date': "{:%Y-%m-%d}".format(
                        form.cleaned_data.get('end_date')),
                }
            ))

        return render(request, self.template_name, {'form': form})


class CoverageView(View):
    template_name = 'front/coverage.html'

    def get(self, request, *args, **kwargs):
        begin_date = datetime.strptime(
            kwargs.get('begin_date'), '%Y-%m-%d')
        end_date = datetime.strptime(
            kwargs.get('end_date'), '%Y-%m-%d')
        destination = kwargs.get('slug')
        product_id = kwargs.get('product_id')

        quotations = Quotation()
        products = Products()

        quotations = quotations.calculate(
            destination=destination,
            begin_date=begin_date,
            end_date=end_date
        )
        quotation = [q for q in quotations if q['code'] == str(product_id)][0]
        quotation = json.dumps(quotation)
        quotation = json2obj(quotation)
        product = products.list(product_id)
        product = json.dumps(product)
        product = json2obj(product)

        destinations = Destinations()

        destinations = destinations.list()

        destination = [e.get('name')
                       for e in destinations if e.get('slug') == destination][0]

        return render(request, self.template_name, {
            'product': product,
            'quotation': quotation,
            'destination': destination,
            'begin_date': begin_date,
            'end_date': end_date
        })


class PurchaseView(View):
    form_class = FormPurchase
    template_name = 'front/purchase.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            begin_date = datetime.strptime(
                kwargs.get('begin_date'), '%Y-%m-%d')
            end_date = datetime.strptime(
                kwargs.get('end_date'), '%Y-%m-%d')
            destination = kwargs.get('slug')
            product_id = kwargs.get('product_id')
            insured_cpf = form.cleaned_data.get('insured_cpf')
            insured_name = form.cleaned_data.get('insured_name')
            insured_birth = form.cleaned_data.get('birth_date')
            card_name = form.cleaned_data.get('card_name')
            card_cpf = form.cleaned_data.get('card_cpf')
            card_number = form.cleaned_data.get('card_number')
            card_mouth = form.cleaned_data.get('card_mouth')
            card_year = form.cleaned_data.get('card_year')
            card_cvv = form.cleaned_data.get('card_cvv')
            buy_name = form.cleaned_data.get('buy_name')
            buy_email = form.cleaned_data.get('buy_email')
            buy_phone = form.cleaned_data.get('buy_phone')

            products = Products()
            product = products.list(product_id)

            quotations = Quotation()
            quotations = quotations.calculate(
                destination=kwargs.get('slug'),
                begin_date=begin_date,
                end_date=end_date
            )
            quotation = [e for e in quotations if e['code'] == product_id][0]

            Purchase.objects.create(
                begin_date=begin_date,
                end_date=end_date,
                destination=destination,
                product_id=product_id,
                insured_cpf=insured_cpf,
                insured_name=insured_name,
                insured_birth=insured_birth,
                card_name=card_name,
                card_cpf=card_cpf,
                card_number=card_number,
                card_mouth=card_mouth,
                card_year=card_year,
                card_cvv=card_cvv,
                buy_name=buy_name,
                buy_email=buy_email,
                buy_phone=buy_phone,
                product_name=product.get('name'),
                provider_name=product.get('provider_name'),
                price=quotation.get('adult').get('price')
            )
            return HttpResponseRedirect(reverse('front:success'))
        return render(request, self.template_name, {'form': form})

purchase/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from purchase.models import Purchase


class ListPurchase(ListView):
    model = Purchase


class DetailPurchase(DetailView):
    model = Purchase

front/templates/front/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <title>{% block title %}Seguros Promo{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" integrity="sha256-I4gvabvvRivuPAYFqevVhZl88+vNf2NksupoBxMQi04=" crossorigin="anonymous" />
    <style>
      body {
        padding-top: 5rem;
      }
      </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'front:home' %}">Seguros Promo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="menu de navegação">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbars">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="{% url 'purchase:list' %}">Compras</a></li>
          <li class="nav-item"><a class="nav-link" href="#atendimento">Atendimento</a></li>
          <li class="nav-item"><a class="nav-link" href="#blog">Blog</a></li>
          <li class="nav-item"><a class="nav-link" href="#afiliados">Afiliados</a></li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      {% if messages %}
          {% for message in messages %}
          <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
      <footer class="footer">
        <p>&copy; Seguros Promo 2017</p>
      </footer>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js" integrity="sha256-TueWqYu0G+lYIimeIcMI8x1m14QH/DQVt4s9m/uuhPw=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/locales/bootstrap-datepicker.pt-BR.min.js" integrity="sha256-QN6KDU+9DIJ/9M0ynQQfw/O90ef0UXucGgKn0LbUtq4=" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

front/templates/front/coverage.html
{% extends 'front/base.html' %}
{% block title %}Início{% endblock %}
{% block content %}
<h1>{{ product.name }} <a href="{% url 'front:order' request.resolver_match.kwargs.product_id request.resolver_match.kwargs.slug request.resolver_match.kwargs.begin_date request.resolver_match.kwargs.end_date %}" class="btn btn-success">Comprar</a></h1>
<div class="">
  <h3>Resumo</h3>
  <p>Seguradora: {{ product.provider_name }} </p>
  <p>Destino: {{ destination   }}</p>
  <p>Início: {{ begin_date|date }}</p>
  <p>Término: {{ end_date|date }}</p>
  <p>Valor: R$ {{ quotation.adult.price|floatformat:2 }} </p>
</div>

<div class="">
  <h3>Benefícios</h3>
  <table class="table">
    <thead>
      <tr></tr>
      <tr></tr>
    </thead>
    {% for benefit in product.benefits %}
    <tbody>
      <tr>
        <td>{{ benefit.name }}</td>
        <td>{{ benefit.coverage }}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock %}

front/templates/front/home.html
{% extends 'front/base.html' %}
{% block title %}Início{% endblock %}
{% block content %}
<h1>Encontre as melhores ofertas de Seguro Viagem da internet</h1>
<form role="form" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
         {{ field.label_tag }} {{ field }}
         <ul>
         {% for error in field.errors %}
           <li><small class="form-text text-muted">{{ error|safe }}</small></li>
         {% endfor %}
         </ul>
     </div>
    {% endfor %}
    <div class="form-group"><button class="btn btn-primary" type="submit">Compare</button></div>
</form>
{% endblock %}
{% block script %}
  <script>
      $(function() {
          $(".date").datepicker({
            language: 'pt-BR',
            startDate: '0',
            autoclose: true
          });
      });
  </script>
{% endblock %}

front/templates/front/purchase.html
{% extends 'front/base.html' %}
{% block title %}Finalizar a compra{% endblock %}
{% block content %}
<h1>Finalizar a compra</h1>
<form role="form" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
         {{ field.label_tag }} {{ field }}
         <ul>
         {% for error in field.errors %}
           <li><small class="form-text text-muted">{{ error|safe }}</small></li>
         {% endfor %}
         </ul>
     </div>
    {% endfor %}
    <div class="form-group"><button class="btn btn-primary" type="submit">Comprar</button></div>
</form>
{% endblock %}
{% block script %}
  <script src="//oss.maxcdn.com/jquery.mask/1.11.4/jquery.mask.min.js"></script>
  <script>
      $(function() {
          $(".date").datepicker({
            language: 'pt-BR',
            autoclose: true
          });
          var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
          },
          spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
              }
          };
          $("#id_buy_phone").mask(SPMaskBehavior, spOptions);
      });
  </script>
{% endblock %}

front/templates/front/quotation.html
{% extends 'front/base.html' %}
{% block title %}Cotação{% endblock %}
{% block content %}
<h3>Encontre as melhores ofertas de Seguro Viagem da internet</h1>
<form role="form" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
         {{ field.label_tag }} {{ field }}
         <ul>
         {% for error in field.errors %}
           <li><small class="form-text text-muted">{{ error|safe }}</small></li>
         {% endfor %}
         </ul>
     </div>
    {% endfor %}
    <div class="form-group"><button class="btn btn-primary" type="submit">Compare</button></div>
</form>
<table class="table">
    <thead>
      <tr>
        <th>SEGURADORA</th>
        <th>PLANO</th>
        <th>DESPESA MÉDICA</th>
        <th>SEGURO BAGAGEM</th>
        <th>TOTAL POR SEGURADO</th>
        <th></th>
      </tr>
    </thead>
    {% for quotation in quotations %}
      <tbody>
        <tr>
            <td>{{ quotation.provider_name }}</td>
            <td>{{ quotation.name }}</td>
            <td>{{ quotation.hospital_care }}</td>
            <td>{{ quotation.luggage_insurance }}</td>
            <td>R$ {{ quotation.adult.price|floatformat:2 }}</td>
            <td><a href="{% url 'front:coverage' quotation.code request.resolver_match.kwargs.slug request.resolver_match.kwargs.begin_date request.resolver_match.kwargs.end_date %}" class="btn btn-success">Selecionar</a></td>
        </tr>
      </tbody>
    {% endfor %}
</table>
{% endblock %}
{% block script %}
  <script>
      $(function() {
          $(".date").datepicker({
            language: 'pt-BR',
            startDate: '0',
            autoclose: true
          });
      });
  </script>
{% endblock %}

front/templates/front/sucess.html
{% extends 'front/base.html' %}
{% block title %}Compra realizada com sucesso{% endblock %}
{% block content %}
<div class="jumbotron">
<h1 class="display-3">Compra realizada com sucesso</h1>
<p><a class="btn btn-success btn-lg" href="{% url 'front:home' %}" role="button">Voltar</a></p>
</div>
{% endblock %}